# 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [78]:
import numpy as np

In [79]:
arr = np.arange(1,11) 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr[0], arr[4], arr[-1]

(1, 5, 10)

In [81]:
arr2 = np.arange(1, 13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
arr2[0][1], arr2[1][2], arr2[2][3]

(2, 7, 12)

In [83]:
arr2[0,1], arr2[1,2], arr2[2,3] #numpy에서는 다차원 indexing

(2, 7, 12)

In [84]:
arr2[-1][-2], arr2[-1,-2]

(11, 11)

## 5-2. 슬라이싱

### 1차원 배열

In [85]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
# 3~끝까지 슬라이싱 ([start:end:step])
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr[2:5]

array([3, 4, 5])

In [88]:
# 처음부터 5까지 슬라이싱
arr[:5]

array([1, 2, 3, 4, 5])

In [89]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
#슬라이싱을 한 후에 값을 변경하면 원본에 영향을 미칠까?
new_arr = arr[:5]
new_arr

array([1, 2, 3, 4, 5])

In [92]:
new_arr[0] = 100
new_arr

array([100,   2,   3,   4,   5])

In [93]:
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [94]:
copy_arr = np.copy(arr)
copy_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

### 2차원 배열

In [95]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
# 첫번째 행을 모두 가져오기
arr2[0], arr2[0, :]

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [97]:
# 세번째 열을 모두 가져오기
arr2[:, 2]

array([ 3,  7, 11])

In [98]:
# 첫번째, 두번째 열을 모두 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [99]:
# [[2, 3]
# [6, 7]] 가져오기
arr2[:2,1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [100]:
# 1차원 배열
arr[0] = 1
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
# 1,3,5로 된 배열을 만들기
np.array([arr[0], arr[2], arr[4]])

array([1, 3, 5])

In [102]:
# 슬라이싱 [start:end:step]
arr[:5:2]

array([1, 3, 5])

In [103]:
# Fancy 인덱싱
arr[[0, 2, 4]]

array([1, 3, 5])

In [104]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
# [[1, 2, 3, 4
#  9, 10, 11, 12]]
np.array([arr2[0], arr2[2]])

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [106]:
# Fancy 인덱싱
arr2[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [107]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
# 슬라이싱
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [109]:
# Fancy 인덱싱
arr2[:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean 인덱싱

In [110]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [111]:
#cond =[False, True, True, False, False, True]
arr[[False, True, False, False, True]]

array([1, 4])

In [112]:
arr > 2

array([False, False, False,  True,  True])

In [113]:
arr[arr > 2]

array([3, 4])

In [114]:
# 짝수만 뽑기
arr % 2 ==0

array([ True, False,  True, False,  True])

In [115]:
arr[arr % 2 == 0]

array([0, 2, 4])

In [126]:
# 0, 3, 4
(arr < 1) | (arr > 2)

array([ True, False, False,  True,  True])

In [122]:
arr[(arr < 1) | (arr > 2)]

array([0, 3, 4])

In [118]:
# 2, 3
(arr > 1) & (arr < 4)

array([False, False,  True,  True, False])

In [119]:
arr[(arr > 1) & (arr < 2)]

array([], dtype=int32)